name: Project CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Publish package
        run: mvn -B -e -Dmaven.wagon.http.pool=false clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}